apiVersion: 1

datasources:
  # Prometheus for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
    uid: prometheus-uid
    
  # Prometheus Federation for long-term metrics
  - name: Prometheus-Federation
    type: prometheus
    access: proxy
    url: http://prometheus-federation:9090
    jsonData:
      timeInterval: 60s
      queryTimeout: 120s
      httpMethod: POST
    uid: prometheus-federation-uid
    
  # Jaeger for distributed tracing
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    uid: jaeger-uid
    
  # Elasticsearch for logs and traces
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: ai-logs-*
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: 80
    uid: elasticsearch-uid