version: '3.8'

services:
  # Neo4j Core Cluster for Fabric Sharding
  neo4j-core-01:
    image: neo4j:5.26-enterprise
    hostname: neo4j-core-01
    container_name: neo4j-core-01
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      
      # Core cluster configuration
      NEO4J_dbms_mode: CORE
      NEO4J_causal__clustering_initial__discovery__members: neo4j-core-01:5000,neo4j-core-02:5000,neo4j-core-03:5000
      NEO4J_causal__clustering_discovery__advertised__address: neo4j-core-01:5000
      NEO4J_causal__clustering_transaction__advertised__address: neo4j-core-01:6000
      NEO4J_causal__clustering_raft__advertised__address: neo4j-core-01:7000
      
      # Fabric configuration for distributed queries
      NEO4J_fabric_database_name: fabric
      NEO4J_fabric_routing_servers: neo4j-core-01:7687,neo4j-core-02:7687,neo4j-core-03:7687
      
      # Performance optimizations for billion-scale
      NEO4J_dbms_memory_heap_initial__size: 8G
      NEO4J_dbms_memory_heap_max__size: 16G
      NEO4J_dbms_memory_pagecache_size: 32G
      NEO4J_dbms_tx__log_rotation_retention__policy: "100M size"
      
      # Clustering timeouts
      NEO4J_causal__clustering_leader__election__timeout: 7s
      NEO4J_causal__clustering_heartbeat__interval: 5s
      
    volumes:
      - neo4j-core-01-data:/data
      - neo4j-core-01-logs:/logs
      - neo4j-core-01-import:/import
      - ./fabric-config:/fabric-config:ro
    networks:
      - neo4j-cluster

  neo4j-core-02:
    image: neo4j:5.26-enterprise
    hostname: neo4j-core-02
    container_name: neo4j-core-02
    ports:
      - "7475:7474"
      - "7688:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      
      NEO4J_dbms_mode: CORE
      NEO4J_causal__clustering_initial__discovery__members: neo4j-core-01:5000,neo4j-core-02:5000,neo4j-core-03:5000
      NEO4J_causal__clustering_discovery__advertised__address: neo4j-core-02:5000
      NEO4J_causal__clustering_transaction__advertised__address: neo4j-core-02:6000
      NEO4J_causal__clustering_raft__advertised__address: neo4j-core-02:7000
      
      NEO4J_fabric_database_name: fabric
      NEO4J_fabric_routing_servers: neo4j-core-01:7687,neo4j-core-02:7687,neo4j-core-03:7687
      
      NEO4J_dbms_memory_heap_initial__size: 8G
      NEO4J_dbms_memory_heap_max__size: 16G
      NEO4J_dbms_memory_pagecache_size: 32G
      NEO4J_dbms_tx__log_rotation_retention__policy: "100M size"
      
      NEO4J_causal__clustering_leader__election__timeout: 7s
      NEO4J_causal__clustering_heartbeat__interval: 5s
      
    volumes:
      - neo4j-core-02-data:/data
      - neo4j-core-02-logs:/logs
      - neo4j-core-02-import:/import
      - ./fabric-config:/fabric-config:ro
    networks:
      - neo4j-cluster

  neo4j-core-03:
    image: neo4j:5.26-enterprise
    hostname: neo4j-core-03
    container_name: neo4j-core-03
    ports:
      - "7476:7474"
      - "7689:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      
      NEO4J_dbms_mode: CORE
      NEO4J_causal__clustering_initial__discovery__members: neo4j-core-01:5000,neo4j-core-02:5000,neo4j-core-03:5000
      NEO4J_causal__clustering_discovery__advertised__address: neo4j-core-03:5000
      NEO4J_causal__clustering_transaction__advertised__address: neo4j-core-03:6000
      NEO4J_causal__clustering_raft__advertised__address: neo4j-core-03:7000
      
      NEO4J_fabric_database_name: fabric
      NEO4J_fabric_routing_servers: neo4j-core-01:7687,neo4j-core-02:7687,neo4j-core-03:7687
      
      NEO4J_dbms_memory_heap_initial__size: 8G
      NEO4J_dbms_memory_heap_max__size: 16G
      NEO4J_dbms_memory_pagecache_size: 32G
      NEO4J_dbms_tx__log_rotation_retention__policy: "100M size"
      
      NEO4J_causal__clustering_leader__election__timeout: 7s
      NEO4J_causal__clustering_heartbeat__interval: 5s
      
    volumes:
      - neo4j-core-03-data:/data
      - neo4j-core-03-logs:/logs
      - neo4j-core-03-import:/import
      - ./fabric-config:/fabric-config:ro
    networks:
      - neo4j-cluster

  # Read Replicas for scaling queries
  neo4j-replica-01:
    image: neo4j:5.26-enterprise
    hostname: neo4j-replica-01
    container_name: neo4j-replica-01
    ports:
      - "7477:7474"
      - "7690:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      
      NEO4J_dbms_mode: READ_REPLICA
      NEO4J_causal__clustering_initial__discovery__members: neo4j-core-01:5000,neo4j-core-02:5000,neo4j-core-03:5000
      
      NEO4J_dbms_memory_heap_initial__size: 4G
      NEO4J_dbms_memory_heap_max__size: 8G
      NEO4J_dbms_memory_pagecache_size: 16G
      
    volumes:
      - neo4j-replica-01-data:/data
      - neo4j-replica-01-logs:/logs
    networks:
      - neo4j-cluster

  neo4j-replica-02:
    image: neo4j:5.26-enterprise
    hostname: neo4j-replica-02
    container_name: neo4j-replica-02
    ports:
      - "7478:7474"
      - "7691:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      
      NEO4J_dbms_mode: READ_REPLICA
      NEO4J_causal__clustering_initial__discovery__members: neo4j-core-01:5000,neo4j-core-02:5000,neo4j-core-03:5000
      
      NEO4J_dbms_memory_heap_initial__size: 4G
      NEO4J_dbms_memory_heap_max__size: 8G
      NEO4J_dbms_memory_pagecache_size: 16G
      
    volumes:
      - neo4j-replica-02-data:/data
      - neo4j-replica-02-logs:/logs
    networks:
      - neo4j-cluster

volumes:
  neo4j-core-01-data:
  neo4j-core-01-logs:
  neo4j-core-01-import:
  neo4j-core-02-data:
  neo4j-core-02-logs:
  neo4j-core-02-import:
  neo4j-core-03-data:
  neo4j-core-03-logs:
  neo4j-core-03-import:
  neo4j-replica-01-data:
  neo4j-replica-01-logs:
  neo4j-replica-02-data:
  neo4j-replica-02-logs:

networks:
  neo4j-cluster:
    driver: bridge